eclipse-symphony/symphony

- api/pkg/apis/v1alpha1/providers/target/helm/helm_test.go
- api/pkg/apis/v1alpha1/providers/target/kubectl/kubectl_test.go
- Remove duplicate deployment of yaml.k8s type in kubectl test case and it was covered `TestKubectlTargetProviderPathApply` and `TestKubectlTargetProviderDelete`. Recreation may cause namespace being terminated while running new deployment. Just test resource type Apply failure in `TestKubectlTargetProviderApplyFailed`.
-  Cleanup `test` file after running download test in helm_test
> Remove duplicate yaml deployment from kubectl_test

- api/pkg/apis/v1alpha1/managers/activations/activations-cleanup-manager.go
- api/pkg/apis/v1alpha1/managers/activations/activations-manager.go
- api/pkg/apis/v1alpha1/managers/activations/activations-manager_test.go
- api/pkg/apis/v1alpha1/managers/managerfactory.go
- api/pkg/apis/v1alpha1/model/campaign.go
- api/pkg/apis/v1alpha1/vendors/backgroundjob-vendor.go
- api/pkg/apis/v1alpha1/vendors/stage-vendor.go
- api/pkg/apis/v1alpha1/vendors/vendorfactory.go
- api/symphony-api-no-k8s.json
- k8s/config/oss/crd/bases/workflow.symphony_activations.yaml
- packages/helm/symphony/files/symphony-api.json
- packages/helm/symphony/templates/symphony.yaml
Issue: https://github.com/Azure/symphony/issues/92
1. Add a new field "UpdateTime" in ActivationStatus, symphony response and k8s activation CRD. New response from symphony core API and k8s activation appearance examples are listed at the end.
2. Leverage existing looping jobs for managers to periodically check activation status and update time and delete old ones from state provider. The frequency of looping jobs can be changed via "loopInterval" and the definition of old activations can be changed via cleanupInterval. Both are defined in symphony core configuration. Currently, we don't support changing it at runtime.
3. Unit test
Test plan:
Unit test. Coverage of activation managers increases from 29.9% to 70.1%
Before
ok github.com/azure/symphony/api/pkg/apis/v1alpha1/managers/activatio …
> Implement cleaner that clear out old activations

- api/pkg/apis/v1alpha1/managers/targets/targets-manager.go
- api/pkg/apis/v1alpha1/managers/targets/targets-manager_test.go
https://github.com/Azure/symphony/issues/206
- dict["spec"] is model.TargetSpec type rather than map[string]interface{}
- Initialize map instance if it's nil. Otherwise, null exception can be hit when adding values.
- Add unit tests
> Fix error in target manager ReportStatus function and add test coverage

- README.md
**Changes**
- Fix badge link in README. Now it's broken.
> Fix go.yaml badge in README

- cli/cmd/up.go
- cli/install/install.ps1
- cli/utils/runcmd.go
**Changes**
1. Improve check minikube in edge cases on Windows. Suppose maestro up failed in the first time. Because the PS session is not started, in second try, even if we detect the k8s connection is connected, we cannot run minikube when starting tunnel since minikube is not found.
2. Found one issue in install.ps1. (should use maestro version, not meastro --version)
3. Only start tunnel in minikube. Also check minikube when starting tunnel. There's an edge case that minikube is not needed to be install because k8s connection is connected with existing minikube cluster. But we still need to check and install minikube in known path for starting a tunnel.
> Improve check minikube in error cases, fix install.ps1 error, only start tunnel in minikube

- api/pkg/apis/v1alpha1/managers/stage/stage-manager.go
https://github.com/eclipse-symphony/symphony/issues/8
In multi-site scenario, parent site depends on the response from child site to determine which stage of which campaign need to be resumed (See stage-manager.go ResumeStage function).
If the fields are not set, symphony on parent site would throw an exception of unable to cast nil to string.
> Stage manager need to set output correctly when job is finished for multi-site scenario

- README.md
- docs/symphony-book/build_deployment/multisite-deploy.md
- docs/symphony-book/quick_start/quick_start_helm.md
- k8s/README.md
- k8s/config/oss/helm/manager-patch.yaml
- packages/helm/symphony/templates/secret.yaml
- packages/helm/symphony/templates/symphony-api.yaml
- packages/helm/symphony/templates/symphony.yaml
- test/localenv/magefile.go
Symphony container images and helm charts are public available now. We don't need imagePullSecrets in deployment.
**Validations**
- Integration tests passed.
- Deployment passed. 
_Warning  FailedToRetrieveImagePullSecret  24m (x39 over 70m)  kubelet            Unable to retrieve some image pull secrets (symphony-regcred); attempting to pull the image may not succeed._ is gone in symphony-controller-manager pod.
- Tested docs/samples/k8s/hello-world sample, passed.
> Remove imagePullSecrets

- api/pkg/apis/v1alpha1/managers/solution/solution-manager.go
Assign deployment as an evaluation context value, so it is exposed in DSL expressions such as ${{$context('$.Instance.Scope')}}. Currently, the evaluation context value is empty while evaluating Solution's properties.
> Deployment as evaluation context value

- api/pkg/apis/v1alpha1/managers/instances/instances-manager_test.go
- api/pkg/apis/v1alpha1/managers/jobs/jobs-manager_test.go
- api/pkg/apis/v1alpha1/managers/solution/solution-manager-state_test.go
- api/pkg/apis/v1alpha1/managers/solution/solution-manager_test.go
- api/pkg/apis/v1alpha1/managers/solutions/solutions-manager_test.go
- api/pkg/apis/v1alpha1/managers/stage/stage-manager_test.go
- api/pkg/apis/v1alpha1/managers/staging/staging-manager_test.go
- api/pkg/apis/v1alpha1/providers/target/mock/mock.go
- api/pkg/apis/v1alpha1/vendors/solution-vendor_test.go
1. Fix mockTargetProvider where get function doesn't filter component name
2. Add UT for several managers
| manager | previous (%) | now (%) |
-------|---------------------------|-------------------------------------------
|campaign| 51.8 | 75|
| instances | / | 78.1 |
|jobs | / | 73.3|
| solution | 62.5 | 75.7|
|solutions | / | 78.0|
|stage | 43.9 | 69.2|
|staging | / | 60.6|
> api managers test coverage improvement

- cli/cmd/p4ectl.go
- cli/cmd/samples.go
- cli/cmd/up.go
- cli/get_helm.sh
- cli/go.mod
- cli/go.sum
- cli/utils/runcmd.go
- docs/symphony-book/quick_start/quick_start_maestro.md
Fix: #71 
Fix: #72 
Fix: #73 
More users start to use maestro CLI and we got some feedback and opened issues #71 #72 #73.
These issues are not always reproduced and most of them can be fixed by retry or users need to get the detailed error information and do some manual mitigation before next retry. But in current maestro CLI, users cannot get the meaningful diagnostic information from output to resolve this issue. And for the transient issues, we don't have any retries. 
So, this PR is trying to,
1. By analyzing existing error patterns, always print the last error in the following error prone paths,
- a. Create minikube cluster
- b. Install cert manager
- c. Deploy symphony by running helm install/upgrade
- d. Run post action step when running samples
3. For path c, d, add retries to …
> Improve the first experience of maestro CLI

- api/pkg/apis/v1alpha1/managers/targets/targets-manager.go
- api/pkg/apis/v1alpha1/vendors/activations-vendor.go
- api/pkg/apis/v1alpha1/vendors/activations-vendor_test.go
- api/pkg/apis/v1alpha1/vendors/campaigns-vendor.go
- api/pkg/apis/v1alpha1/vendors/campaigns-vendor_test.go
- api/pkg/apis/v1alpha1/vendors/instances-vendor.go
- api/pkg/apis/v1alpha1/vendors/instances-vendor_test.go
- api/pkg/apis/v1alpha1/vendors/job-vendor.go
- api/pkg/apis/v1alpha1/vendors/job-vendor_test.go
- api/pkg/apis/v1alpha1/vendors/solution-vendor.go
- api/pkg/apis/v1alpha1/vendors/solution-vendor_test.go
- api/pkg/apis/v1alpha1/vendors/solutions-vendor.go
- api/pkg/apis/v1alpha1/vendors/solutions-vendor_test.go
- api/pkg/apis/v1alpha1/vendors/stage-vendor_test.go
- api/pkg/apis/v1alpha1/vendors/staging-vendor_test.go
- api/pkg/apis/v1alpha1/vendors/targets-vendor.go
- api/pkg/apis/v1alpha1/vendors/targets-vendor_test.go
- api/pkg/apis/v1alpha1/vendors/vendorfactory_test.go
1. Improve vendor logging.
2. Test coverage improvements:
| components | previous(%) | now (%)|
|---------------|------------|-------|
| activations-vendor| / | 70.3|
|instances-vendor|/ | 84.0|
|job-vendor| /|59.1|
|staging-vendor| /|38.5|
|vendorfactory| /|95.5|
|solution-vendor| 50.7|82.4|
|stage-vendor| /| 68.9|
|solutions-vendor|0 | 79.7|
|targets-vendor|/|74.0|
|campaigns-vendor|0 | 81.1|
> Add unit tests for part of vendors

- api/pkg/apis/v1alpha1/providers/states/k8s/k8s.go
- api/pkg/apis/v1alpha1/providers/states/k8s/k8s_test.go
- coa/pkg/apis/v1alpha2/providers/states/httpstate/httpstate.go
- coa/pkg/apis/v1alpha2/providers/states/httpstate/httpstate_test.go
- Guard request.ID null in Get, Upsert, Delete functions in k8sand http state provider.
Discussion: should we guard null in memory state provider as well? Although empty key is allowed in the in-memory dictionary, storing and deleting states with empty key may cause operation conflicts for example deleting with unexpected empty ID makes that stored by others deleted.
> Guard invalid null request ID in http and k8s state providers

- api/pkg/apis/v1alpha1/providers/providerfactory.go
- api/pkg/apis/v1alpha1/providers/providerfactory_test.go
- api/pkg/apis/v1alpha1/providers/stage/create/create.go
- api/pkg/apis/v1alpha1/providers/stage/create/create_test.go
- api/pkg/apis/v1alpha1/providers/stage/delay/delay_test.go
- api/pkg/apis/v1alpha1/providers/stage/http/http.go
- api/pkg/apis/v1alpha1/providers/stage/http/http_test.go
- api/pkg/apis/v1alpha1/providers/stage/list/list.go
- api/pkg/apis/v1alpha1/providers/stage/list/list_test.go
- api/pkg/apis/v1alpha1/providers/stage/materialize/materialize_test.go
- api/pkg/apis/v1alpha1/providers/stage/mock/mock_test.go
- api/pkg/apis/v1alpha1/providers/stage/patch/patch_test.go
- api/pkg/apis/v1alpha1/providers/stage/remote/remote_test.go
- api/pkg/apis/v1alpha1/providers/stage/script/script_test.go
- api/pkg/apis/v1alpha1/providers/stage/wait/wait_test.go
1. minor fix for a few issues:
1). https://github.com/eclipse-symphony/symphony/issues/107
2). https://github.com/eclipse-symphony/symphony/issues/103
3). providerfactory doesn't return provider for "providers.stage.delay"
2. add unit tests for some providers
| components | previous(%) | now (%)|
|---------------|------------|-------|
|providerfactory.go | /| 82.3|
|stage/wait/wait.go|/| 91.3|
|stage/create/create.go|/ |89.6|
|stage/list/list.go| /| 90.0|
|stage/script/script.go| 49.5| 78.1|
|stage/delay/delay.go| /| 90.2|
|stage/remote/remote.go|/ | 83.3|
|stage/mock/mock.go|/ | 91.5|
|stage/http/http.go| 46.4|71.3 |
|stage/patch/patch.go| /| 65.3|
|stage/counter/counter.go | 69.5| 69.5|
|stage/materialize/materialize.go|/ | 86.2|
> unit tests for stage providers

- .github/workflows/go.yml
- api/pkg/apis/v1alpha1/providers/states/k8s/k8s.go
- api/pkg/apis/v1alpha1/providers/states/k8s/k8s_test.go
This reverts commit 3bc65dd0bcfc39d7f90391f4d456190a09c5f9e2.
Symphony objects Target and Activation have structure for status object and the previous change will break activation logic.
> Revert "Fix k8s state provider update status logic and add unit tests"

- coa/pkg/apis/v1alpha2/bindings/http/http_pipeline.go
- coa/pkg/apis/v1alpha2/bindings/http/http_pipeline_test.go
- coa/pkg/apis/v1alpha2/bindings/http/http_test.go
- coa/pkg/apis/v1alpha2/bindings/http/jwt_test.go
- coa/pkg/apis/v1alpha2/bindings/http/telemetry.go
- coa/pkg/apis/v1alpha2/bindings/http/tracing.go
- coa/pkg/apis/v1alpha2/bindings/http/tracing_test.go
- coa/pkg/apis/v1alpha2/bindings/mqtt/mqtt_test.go
- coa/pkg/apis/v1alpha2/observability/observability.go
- coa/pkg/apis/v1alpha2/safebuffer.go
- coa/pkg/apis/v1alpha2/safebuffer_test.go
**Changes**
- Fix #128 
- Add more tests
Files | Previous (%) | Now (%) | Notes
-- | -- | -- | --
./pkg/apis/v1alpha2/bindings/http/jwt.go | 0 | 90.3 |  
./pkg/apis/v1alpha2/bindings/http/trail.go | 0 | 100 |  
./pkg/apis/v1alpha2/bindings/http/telemetry.go | 0 | 82.4 | ENABLE_APP_INSIGHT and APP_INSIGHT_KEY configured
./pkg/apis/v1alpha2/bindings/http/cors.go | 0 | 100 |  
./pkg/apis/v1alpha2/bindings/http/http_pipeline.go | 0 | 97.4 |  
./pkg/apis/v1alpha2/bindings/http/tracing.go | 65.8 | 75 |  
./pkg/apis/v1alpha2/bindings/http/http.go | 0 | 87.5 |  
./pkg/apis/v1alpha2/bindings/mqtt/mqtt.go | 67.6 | 85.3 |  
> Fix middleware.http.telemetry config parser issue and add tests

- coa/pkg/apis/v1alpha2/providers/probe/rtsp/rtsp.go
- docs/symphony-book/agent/symphony-agent.md
Fix #159 
Also found symphony-agent doc lacks a step to guide users to grant rbac to access storage account.
Tested symphony-agent sample - https://github.com/eclipse-symphony/symphony/blob/main/docs/symphony-book/agent/symphony-agent.md.
> Return err when rtsp server is disconnected

- api/pkg/apis/v1alpha1/managers/sync/sync-manager.go
- api/pkg/apis/v1alpha1/vendors/catalogs-vendor.go
- api/pkg/apis/v1alpha1/vendors/catalogs-vendor_test.go
Fix https://github.com/eclipse-symphony/symphony/issues/141
The fix affects catalog synchronization from parent sites to child sites.
Previously catalogs on child site are named as catalog.Spec.SiteId-catalog.Spec.Name.
Now change it to parentSiteId-catalog.Spec.Name.
The change is tested on catalog synchronization between two sites.
> catalog prefix using parent site name

- api/pkg/apis/v1alpha1/providers/target/mqtt/mqtt.go
- api/pkg/apis/v1alpha1/providers/target/mqtt/mqtt_test.go
Previously, an MQTT Target Provider component's summary spec would always return `9998` for its status and an empty message. 
`ret` is assigned but never updated in the MQTT Target Provider: https://github.com/eclipse-symphony/symphony/blob/main/api/pkg/apis/v1alpha1/providers/target/mqtt/mqtt.go#L340
This PR updates `ret` in the MQTT Target Provider according to what the target returns:
> Update MQTT Target Provider's Status and Message

- k8s/magefile.go
setup-envtest module bumped its golang version to 1.22.0 recently. 
By checking the go.mod, we can found the last available version to golang 1.20.2 is **v0.0.0-20240320141353-395cfc7486e6**, we need to pin to this version since symphony-k8s image uses golang:1.20.2-alpine (golang 1.20.2)
https://pkg.go.dev/sigs.k8s.io/controller-runtime/tools/setup-envtest@v0.0.0-20240320141353-395cfc7486e6?tab=versions
Otherwise building k8s image will fail at running mage operatorTest. 
**v0.0.0-20240320141353-395cfc7486e6**: https://github.com/kubernetes-sigs/controller-runtime/blob/395cfc7486e652d19fe1b544a436f9852ba26e4f/tools/setup-envtest/go.mod
**latest**: https://github.com/kubernetes-sigs/controller-runtime/blob/main/tools/setup-envtest/go.mod
> Pin setup-envtest version to fit golang 1.20.2

- api/pkg/apis/v1alpha1/vendors/activations-vendor_test.go
- api/pkg/apis/v1alpha1/vendors/campaigns-vendor_test.go
- api/pkg/apis/v1alpha1/vendors/solutions-vendor_test.go
- coa/pkg/apis/v1alpha2/providers/states/memorystate/memorystate.go
- coa/pkg/apis/v1alpha2/providers/states/memorystate/memorystate_test.go
Previously, memory state provider maintained a map of objects. The key is the object name, and the value is the object. 
Memory state provider is also used when running on k8s cluster, for example, storing heartbeat of a job or sync cache of catalogs.
In these scenarios, objects need to be stored under namespace scope. 
Test:
- Add new unit tests for upsert, get, delete, list (single namespace or all namespaces)
- Pass integration tests.
> Support different namespace for memory state provider

- docs/symphony-book/concepts/unified-object-model/campaign.md
- docs/symphony-book/concepts/unified-object-model/solution.md
Some of the links in the Symphony Book documentation were broken.  I attempted to link to the correct locations.
> Fixes Some Links in the Symphony Book Documentation

- api/pkg/apis/v1alpha1/providers/target/proxy/proxy.go
Previously, an HTTP Proxy Target Provider component's summary spec would always return 9998 for its status and an empty message: 
The `ret` variable is assigned but never updated in the HTTP Proxy Target Provider: https://github.com/eclipse-symphony/symphony/blob/main/api/pkg/apis/v1alpha1/providers/target/proxy/proxy.go#L163
This PR updates `ret` variable in the HTTP Proxy Target Provider according to what the target returns:
> Add response status and message in the target's http proxy apply()

- api/pkg/apis/v1alpha1/managers/activations/activations-manager.go
- api/pkg/apis/v1alpha1/managers/campaigns/campaigns-manager.go
- api/pkg/apis/v1alpha1/managers/catalogs/catalogs-manager.go
- api/pkg/apis/v1alpha1/managers/devices/devices-manager.go
- api/pkg/apis/v1alpha1/managers/instances/instances-manager.go
- api/pkg/apis/v1alpha1/managers/jobs/jobs-manager.go
- api/pkg/apis/v1alpha1/managers/models/models-manager.go
- api/pkg/apis/v1alpha1/managers/sites/sites-manager.go
- api/pkg/apis/v1alpha1/managers/skills/skills-manager.go
- api/pkg/apis/v1alpha1/managers/solution/solution-manager.go
- api/pkg/apis/v1alpha1/managers/solutions/solutions-manager.go
- api/pkg/apis/v1alpha1/managers/stage/stage-manager.go
- api/pkg/apis/v1alpha1/managers/staging/staging-manager.go
- api/pkg/apis/v1alpha1/managers/targets/targets-manager.go
- api/pkg/apis/v1alpha1/managers/users/users-manager.go
- coa/pkg/apis/v1alpha2/providers/states/memorystate/memorystate.go
1. memory state provide return a deep copy of objects using Marshal and then Unmarshal (get and list)
2. Use same error in managers so that CloseSpanWithError can get the right error
> memory state provider return deep copy of objects

- cli/cmd/up.go
- cli/install/install.ps1
- cli/install/install.sh
Removed Docker check as we are currently not using it for either no-k8s or k8s version. We may need it again when we add run-in-docker option.
Also remove the auto-added 'v' prefix if user specifies a version number, as our releases don't have the 'v' prefix in the repo.
> remove Docker check; remove 'v' prefix of version parameter

- .github/workflows/release.yaml
**Context:**
https://github.com/eclipse-symphony/.eclipsefdn/pull/4
Suggestions by eclipse forks:
> so I see that you request these changes in order to support your release workflow that fails now.
> 
> This is a common problem with github actions and can not be easily solved by a bypass rule for github actions, as there is no user like that.
> 
> However, what we have done for other projects and is also good practice is the following:
> 
> * inject a token as secret that allows to bypass the branch protection rule
> * add the eclipse-symphoy-bot user to the bypass list (as already done in this PR)
> * disable status checks as this is not compatible with direct pushes
> * adapt your release workflow like that:
>   
>   * https://github.com/eclipse-xpanse/xpanse-ui/blob/main/.github/workflo …
> Use BOT_USER (eclipse-symphoy-bot) to checkout, commit, push changes in release pipeline

- .github/workflows/release.yaml
This is a follow up of #247 .
I have seen that the latest release still committed using actions@github.com user information and inspected the workflow. In fact the user and email was set twice in the workflow, this PR fixes that to use the correct username.
@msftcoderdjw
> Correctly setup commit user and email in release workflow

- api/pkg/apis/v1alpha1/managers/activations/activations-manager_test.go
- api/pkg/apis/v1alpha1/managers/stage/stage-manager.go
- api/pkg/apis/v1alpha1/managers/stage/stage-manager_test.go
- api/pkg/apis/v1alpha1/model/campaign.go
- api/pkg/apis/v1alpha1/vendors/activations-vendor_test.go
- api/pkg/apis/v1alpha1/vendors/federation-vendor_test.go
- api/pkg/apis/v1alpha1/vendors/stage-vendor.go
- api/pkg/apis/v1alpha1/vendors/stage-vendor_test.go
- coa/pkg/apis/v1alpha2/types.go
- docs/samples/opera/app/types.d.ts
- docs/samples/opera/components/campaigns/CampaignCard.tsx
- k8s/apis/workflow/v1/activation_types.go
- k8s/config/oss/crd/bases/workflow.symphony_activations.yaml
- packages/helm/symphony/templates/symphony-core/symphonyk8s.yaml
```yaml
$ kubectl get activation
NAME         NEXT STAGE   STATUS
04workflow                Done  // printColumn will use statusMessage to display.
$ kubectl describe activation
Name:         04workflow
Namespace:    default
Labels:       <none>
Annotations:  <none>
API Version:  workflow.symphony/v1
Kind:         Activation
Metadata:
Creation Timestamp:  2024-05-11T02:29:08Z
Generation:          1
Resource Version:    1239
UID:                 cf8dfab3-ec72-49af-b1e1-de7478563487
Spec:
Campaign:  04campaign
Status:
Outputs:
__activation:            04workflow
__activationGeneration:  1
__campaign:              04campaign
__namespace:             default
__site:                  hq
__stage:                 deploy
__status:                200
Stage:                     deploy
Status: …
```
> Add statusMessage in activation for better display

- .github/workflows/integration.yml
- .github/workflows/suite.yml
- api/Dockerfile
- api/magefile.go
- k8s/Dockerfile
- packages/helm/symphony/values.yaml
- packages/mage/mage.go
- test/localenv/magefile.go
- test/localenv/symphony-ghcr-values.yaml
Changes:
1. Based on the review requirements, we need to use different base images to generate Symphony-api and Symphony-k8s for Azure builds. So include base image ARG in dockerfile and provider override mage utility functions.
2. Provide ways to customize integration tests. 
3. Fix typos and unused `imagePrivateRegistryUrl`.
> Customize image build and integration test

- packages/helm/symphony/files/symphony-api.json
- packages/helm/symphony/templates/redis-configmap.yaml
- packages/helm/symphony/templates/redis.yaml
- packages/helm/symphony/templates/symphony-core/_helpers.tpl
- packages/helm/symphony/templates/symphony-core/symphony-api.yaml
- packages/helm/symphony/values.yaml
> Support redis as sidecar of Symphony API pod

- api/constants/constants.go
- api/constants/eula.txt
Better to read eula message from file.
We need this change since the downstream arc extension needs different eula message.
> Read eula message from file

- api/pkg/apis/v1alpha1/managers/activations/activations-manager.go
- api/pkg/apis/v1alpha1/providers/states/k8s/k8s.go
- api/pkg/apis/v1alpha1/vendors/stage-vendor.go
- k8s/apis/workflow/v1/activation_webhook.go
- k8s/config/oss/webhook/manifests.yaml
- k8s/main.go
- packages/helm/symphony/templates/symphony-core/symphonyk8s.yaml
- test/integration/scenarios/04.workflow/magefile.go
- test/integration/scenarios/04.workflow/manifest/activation-campaignnotexist.yaml
- test/integration/scenarios/04.workflow/manifest/activation-stage.yaml
- Add validation webhook that block creating activation if the campaign doesn't exist
- Fix https://github.com/eclipse-symphony/symphony/issues/300 in stage-vendor.go
> Add webhook for activation in case campaign doesn't exist

- cli/cmd/up.go
The Maestro CLI tool does not set these environment variables `SYMPHONY_API_URL` and `USE_SERVICE_ACCOUNT_TOKENS`, whereas the Symphony API binary does (https://github.com/eclipse-symphony/symphony/blob/main/docs/symphony-book/get-started/quick_start_binary.md?plain=1#L24).
I would receive the following error when running Maestro:
```bash
ERRO[0014]  M (Job): error getting instance target-runtime-remote-cmd-instance, namespace: default: Post "http://symphony-service:8080/v1alpha2/users/auth"
```
The hostname `symphony-service` cannot be resolved so the error occurs.
I've added two lines to set the required environment variables when running in `noK8s` mode
> Set env variables for noK8s mode in the Maestro CLI tool

- test/localenv/magefile.go
Old minikube has some issues to load docker image directly so we made a workaround to first save the docker image to local tar and then let minikube load tar file. The issue has been fixed in the latest minikube release 1.33.1 so change it back.
> Let Minikube load image from docker

- api/pkg/apis/v1alpha1/managers/jobs/jobs-manager.go
- api/pkg/apis/v1alpha1/managers/jobs/jobs-manager_test.go
- api/pkg/apis/v1alpha1/managers/solution/solution-manager.go
- api/pkg/apis/v1alpha1/vendors/job-vendor_test.go
- api/pkg/apis/v1alpha1/vendors/solution-vendor_test.go
- api/symphony-api-dev-console-trace.json
- api/symphony-api-dev-zipkin-trace.json
- api/symphony-api-dev.json
- api/symphony-api-no-k8s-munchen.json
- api/symphony-api-no-k8s-new-york.json
- api/symphony-api-no-k8s-tokyo.json
- api/symphony-api-no-k8s.json
- api/symphony-api-production.json
- api/symphony-api-test.json
- api/symphony-api.json
- api/symphony-k8s-poll-agent.json
- api/symphony-k8s-proxy-mqtt.json
- api/symphony-powershell-over-mqtt.json
- api/symphony-script-over-mqtt.json
- api/symphony-script-proxy.json
- api/symphony-win-proxy.json
- k8s/main.go
- packages/helm/symphony/files/symphony-api.json
There are two objects that we are storing in memory should be persistent. 
One is SolutionManagerDeploymentState. It tracks the previous deployment state which is used in three-way merge.
The other is scheduled stage event. It tracks when a scheduled stage should be triggered. Also fixed issue https://github.com/eclipse-symphony/symphony/issues/256 as part of the change.
> Use persistent state store in Job and Solution manager

- api/pkg/apis/v1alpha1/contexts/vendor-context_test.go
- api/pkg/apis/v1alpha1/managers/stage/stage-manager.go
- api/pkg/apis/v1alpha1/managers/stage/stage-manager_test.go
- api/pkg/apis/v1alpha1/model/campaign.go
- api/pkg/apis/v1alpha1/model/objectmeta.go
- api/pkg/apis/v1alpha1/providers/stage/counter/counter.go
- api/pkg/apis/v1alpha1/providers/states/k8s/k8s.go
- api/pkg/apis/v1alpha1/utils/parser.go
- api/pkg/apis/v1alpha1/utils/utils.go
- api/pkg/apis/v1alpha1/utils/utils_test.go
- api/pkg/apis/v1alpha1/vendors/catalogs-vendor.go
- api/pkg/apis/v1alpha1/vendors/stage-vendor.go
- coa/pkg/apis/v1alpha2/errors.go
- coa/pkg/apis/v1alpha2/events.go
- coa/pkg/apis/v1alpha2/providers/pubsub/memory/memory.go
- coa/pkg/apis/v1alpha2/providers/pubsub/memory/memory_test.go
- coa/pkg/apis/v1alpha2/providers/pubsub/redis/redis.go
Fix https://github.com/eclipse-symphony/symphony/issues/306
1. Add EventShouldRetryWrapper which check handler error type and decide whether pubsub provider should retry the handler
2. Add retry mechanism to memory pubsub with retry max count and retry interval.
3. Add max retry count to redis pubsub so events won't stay in redis server forever
4. Unify return error type as COAError with appropriate status code
> Pubsub stop retry for nonretriable errors and add max retry count in memory&redis pubsub

- packages/helm/symphony/templates/redis-configmap.yaml
Only enable appendonly config when persistent volume is present.
> Change appendonly config for redis

- api/pkg/apis/v1alpha1/managers/activations/activations-manager.go
- api/pkg/apis/v1alpha1/model/campaign.go
- coa/pkg/apis/v1alpha2/providers/states/redisstate/redisstate.go
- k8s/apis/workflow/v1/activation_types.go
- k8s/config/oss/crd/bases/workflow.symphony_activations.yaml
- packages/helm/symphony/templates/symphony-core/symphonyk8s.yaml
- test/integration/scenarios/04.workflow/manifest/campaign.yaml
- Change k8s Activation Custom resource
- stagehistory -> stageHistory
- remove unneeded errorMessage field
- Change activation status to Paused if latest stage status is paused
- Change redis state provider separator to "*" since ":" can be used by reference
> Workflow fixes

- README.md
fix readme command to run symphony via docker. bumped the recommended version to 0.48.28.
container comes up as expected:
without the readme fix:
validated the helm deploy also works with the new version (just in case):
> fix readme command to run symphony via docker

- api/pkg/apis/v1alpha1/managers/configs/configs-manager.go
- api/pkg/apis/v1alpha1/managers/configs/configs-manager_test.go
- api/pkg/apis/v1alpha1/managers/secrets/secrets-manager.go
- api/pkg/apis/v1alpha1/providers/config/catalog/catalogprovider.go
- api/pkg/apis/v1alpha1/providers/config/catalog/catalogprovider_test.go
- api/pkg/apis/v1alpha1/providers/secret/k8s.go
- api/pkg/apis/v1alpha1/providers/secret/k8s_test.go
- api/pkg/apis/v1alpha1/vendors/settings-vendor_test.go
- coa/pkg/apis/v1alpha2/providers/config/config.go
- coa/pkg/apis/v1alpha2/providers/config/memoryconfig/memoryconfig.go
- coa/pkg/apis/v1alpha2/providers/config/memoryconfig/memoryconfig_test.go
- coa/pkg/apis/v1alpha2/providers/secret/conformance/secret_conformance.go
- coa/pkg/apis/v1alpha2/providers/secret/mock/mockprovider.go
- coa/pkg/apis/v1alpha2/providers/secret/mock/mockprovider_test.go
- coa/pkg/apis/v1alpha2/providers/secret/secret.go
Since jiawei's tracing PR, config secret manager and provider should follow the same way.
If we want to pass context to manager level, evaluationContext needs to add a context field. We shall make sure evaluationContext clone using the same evaluationContext's context and pass down and make sure it never reused. Change maybe a little bit heavy.
> using new tracing for config and secret managers and providers

- api/pkg/apis/v1alpha1/managers/configs/configs-manager_test.go
- api/pkg/apis/v1alpha1/providers/config/catalog/catalogprovider.go
https://github.com/eclipse-symphony/symphony/issues/420
> Add trace value in unwinding parent catalogs

- api/pkg/apis/v1alpha1/managers/activations/activations-manager.go
- api/pkg/apis/v1alpha1/managers/activations/activations-manager_test.go
- api/pkg/apis/v1alpha1/managers/campaigns/campaigns-manager.go
- api/pkg/apis/v1alpha1/managers/campaigns/campaigns-manager_test.go
- api/pkg/apis/v1alpha1/managers/catalogs/catalogs-manager.go
- api/pkg/apis/v1alpha1/managers/catalogs/catalogs-manager_test.go
- api/pkg/apis/v1alpha1/managers/instances/instances-manager.go
- api/pkg/apis/v1alpha1/managers/solutions/solutions-manager.go
- api/pkg/apis/v1alpha1/managers/solutions/solutions-manager_test.go
- api/pkg/apis/v1alpha1/managers/targets/targets-manager.go
- api/pkg/apis/v1alpha1/managers/targets/targets-manager_test.go
There are some issues for object validation in standalone mode. Details can be found in https://github.com/eclipse-symphony/symphony/issues/445.
Turn off the validation temporarily to unblock object creation.
> Turn off validation in standalone mode for cross type check

- api/pkg/apis/v1alpha1/managers/campaigns/campaigns-manager.go
- k8s/apis/workflow/v1/campaign_webhook.go
- test/integration/scenarios/08.webhook/manifest/campaignLongRunning.yaml
- test/integration/scenarios/08.webhook/verify/webhook_test.go
Campaign update and delete will be only block when there is any running activation on it. If activation enters termination state like DONE, Internal error or bad request, it will not block campaign update and delete anymore.
> Block campaign update and delete with running activation

- api/pkg/apis/v1alpha1/providers/stage/materialize/materialize.go
- api/pkg/apis/v1alpha1/providers/stage/materialize/materialize_test.go
* **Catalog Retrieval Logic**:
- Changed from retrieving all catalogs at once to retrieving catalogs individually, which now uses a map to store catalog states.
- Updated error handling to continue processing other catalogs if one fails, rather than terminating the entire process.
* **Object Creation Tracking**:
- Replaced `creationCount` with a `createdObjectList` map to track successfully created objects more accurately.
* **Error Messaging**:
- Enhanced error messages to specify which objects failed to be created.
* **Mock Symphony API**:
- Updated mock responses to return individual catalog states instead of a list of catalogs, aligning with the new catalog retrieval logic.
Fix #418
> check every single catalog instead of getting the list

- api/pkg/apis/v1alpha1/providers/stage/materialize/materialize.go
Sort the materialize objects by their catalogType and put instance catalogs at last. 
It's because instance may have dependencies on solution and target object. We need to materialize dependencies first so instance creation won't be blocked by webhook check.
> Materialize stage provider respects input order

- api/pkg/apis/v1alpha1/managers/configs/configs-manager.go
- api/pkg/apis/v1alpha1/managers/configs/configs-manager_test.go
- api/pkg/apis/v1alpha1/managers/jobs/jobs-manager.go
- api/pkg/apis/v1alpha1/managers/secrets/secrets-manager.go
- api/pkg/apis/v1alpha1/managers/secrets/secrets-manager_test.go
- api/pkg/apis/v1alpha1/providers/config/catalog/catalogprovider.go
- api/pkg/apis/v1alpha1/providers/stage/http/http.go
- api/pkg/apis/v1alpha1/providers/stage/patch/patch.go
- api/pkg/apis/v1alpha1/utils/parser.go
- api/pkg/apis/v1alpha1/utils/parser_test.go
- api/pkg/apis/v1alpha1/utils/schema.go
- api/pkg/apis/v1alpha1/utils/schema_test.go
- api/pkg/apis/v1alpha1/utils/symphony-api.go
- api/pkg/apis/v1alpha1/utils/symphony-api_test.go
- api/pkg/apis/v1alpha1/validation/catalog_validator.go
- api/pkg/apis/v1alpha1/vendors/settings-vendor.go
- coa/pkg/apis/v1alpha2/providers/config/config.go
- coa/pkg/apis/v1alpha2/providers/config/mock/mockprovider.go
- coa/pkg/apis/v1alpha2/providers/config/mock/mockprovider_test.go
- coa/pkg/apis/v1alpha2/providers/secret/mock/mockprovider.go
- coa/pkg/apis/v1alpha2/providers/secret/secret.go
- coa/pkg/apis/v1alpha2/utils/utils_test.go
- k8s/controllers/fabric/target_controller.go
- k8s/utils/symphony-api.go
- Added context logs for catalog provider
- Updated logs in configs and secrets manager
- Went through parser.go and add logs in the recursive functions. Errors in internal functions will be returned and be handled and logged in `evalProperties` and `enumerateProperties`.
> Add logs for catalog

- packages/helm/symphony/templates/redis.yaml
- packages/helm/symphony/templates/symphony-core/_helpers.tpl
- packages/helm/symphony/values.yaml
Kubernetes uses default storage class when creating PVCs if it doesn't specify storage class name explicitly. However, things are different when updating PVCs with empty storage class name and kubernetes will complain the PVC spec is immutable. 
This PR is to provide better user experience to allow user to enter empty storage class name in both create and update case. In helper function RedisPVCStorageClassName, we will use input if storage class is explicitly specified. Otherwise, it will check if PVC already exist and use the storage class of existing PVC. 
Manually test update scenario for storage class name
empty -> empty
empty -> specified
specified -> empty
specified -> specified
> Use existing storageclass if not specified

- k8s/magefile.go
cherry-pick https://github.com/eclipse-symphony/symphony/commit/d4d4a3f3dcbfda334c8ec0cd7ce267685fcce943 to pp1 release branch
> [release/pp1] workaround: setup-envtest version set to be 0.19 (#514)

- api/pkg/apis/v1alpha1/managers/activations/activations-manager.go
- api/pkg/apis/v1alpha1/managers/stage/stage-manager.go
- api/pkg/apis/v1alpha1/providers/stage/http/http.go
Fix #417
Improvements to activation stage handling:
* [`api/pkg/apis/v1alpha1/managers/activations/activations-manager.go`](diffhunk://#diff-2cab4467559ea7d3b0c380f47d1af1e0c24291c0fe7c84f4db3f7a9394587434R42-R49): Added constants for stage output size limits and activation history size.
* [`api/pkg/apis/v1alpha1/managers/activations/activations-manager.go`](diffhunk://#diff-2cab4467559ea7d3b0c380f47d1af1e0c24291c0fe7c84f4db3f7a9394587434L326-R370): Modified the `mergeStageStatus` function to handle large outputs by truncating inputs/outputs and managing activation stage history.
Dependency updates:
* [`api/pkg/apis/v1alpha1/providers/stage/http/http.go`](diffhunk://#diff-c741559dd8fb19c4853d36525a7594c7bdca81b8d721d517f24218fe3e52bdb8L14-R14): Replaced `ioutil` package functions with …
> truncate input/output/stagehistory when merging activation stages + remove response header in status outputs

- api/pkg/apis/v1alpha1/managers/solution/solution-manager.go
Why this change:
Redis pubsub can have multiple workers so it is possible that two versions of Deployment on the same object are kicked off very closely. And sometimes the newer version gets the reconcile lock before the old one. In this case, the old one should not run reconcile as it's out of date. We use deployment generation to check that.
This change includes:
1. Re-define the generation in deployment as a combination of instance generation, solution generation and target generation. If the instance is linked more than one target, the target generation is the sum of all target generations. (It's very unlikely that the sum is greater than int64)
2. solution reconcile in symphony API check the generation of current deployment and the existing summary.
> Block solution deployment with old generation

- api/pkg/apis/v1alpha1/contexts/manager-context_test.go
- api/pkg/apis/v1alpha1/contexts/vendor-context_test.go
- api/pkg/apis/v1alpha1/managers/catalogs/catalogs-manager_test.go
- api/pkg/apis/v1alpha1/managers/sync/sync-manager_test.go
- api/pkg/apis/v1alpha1/providers/stage/remote/remote_test.go
- api/pkg/apis/v1alpha1/vendors/activations-vendor_test.go
- api/pkg/apis/v1alpha1/vendors/catalogs-vendor.go
- api/pkg/apis/v1alpha1/vendors/echovendor.go
- api/pkg/apis/v1alpha1/vendors/federation-vendor.go
- api/pkg/apis/v1alpha1/vendors/federation-vendor_test.go
- api/pkg/apis/v1alpha1/vendors/instances-vendor_test.go
- api/pkg/apis/v1alpha1/vendors/job-vendor.go
- api/pkg/apis/v1alpha1/vendors/job-vendor_test.go
- api/pkg/apis/v1alpha1/vendors/solution-vendor_test.go
- api/pkg/apis/v1alpha1/vendors/stage-vendor.go
- api/symphony-api-production.json
- coa/pkg/apis/v1alpha2/contexts/manager-context_test.go
- coa/pkg/apis/v1alpha2/contexts/vendor-context_test.go
- coa/pkg/apis/v1alpha2/events.go
- coa/pkg/apis/v1alpha2/providers/pubsub/memory/memory_test.go
- coa/pkg/apis/v1alpha2/providers/pubsub/redis/redis.go
- coa/pkg/apis/v1alpha2/providers/pubsub/redis/redis_test.go
- packages/helm/symphony/files/symphony-api.json
Previous design of redis pubsub maintain an in-memory Queue which contains pending message. However, it requires extra effects to maintain the queue. For example, we need to dedup pending messages if they are already in the queue and we need to be very careful about the locks.
To remove this queue and simplify the logic of redis pubsub, changes are made below
1. We maintain a number of idle workers. Each time when new messages or pending messages are ready, we will try to decrement the number of idle workers so that we can launch a new thread to process the message. And the worker is released back to pool once the thread is done.
2. When a message is being processed, another heartbeat thread will reclaim this message frequently which reset the idleTime of the message and prevent it being …
> Rewrite Redis pubsub

- api/pkg/apis/v1alpha1/managers/stage/stage-manager.go
- api/pkg/apis/v1alpha1/managers/stage/stage-manager_test.go
- api/pkg/apis/v1alpha1/utils/parser.go
- api/pkg/apis/v1alpha1/utils/parser_test.go
- coa/pkg/apis/v1alpha2/utils/utils.go
- docs/samples/campaigns/counter/campaign.yaml
- docs/samples/campaigns/hello-world/campaign.yaml
- docs/samples/campaigns/mock/activation.yaml
- docs/symphony-book/concepts/unified-object-model/campaign.md
- docs/symphony-book/concepts/unified-object-model/property-expressions.md
- test/integration/scenarios/04.workflow/manifest/activation-stage.yaml
- test/integration/scenarios/04.workflow/manifest/activation.yaml
- test/integration/scenarios/04.workflow/manifest/campaign.yaml
Fix https://github.com/eclipse-symphony/symphony/issues/183
Previous discussion: https://github.com/eclipse-symphony/symphony/pull/352
* Added an `apiClient` field to `StageManager` and initialized it in the `Init` function. (`api/pkg/apis/v1alpha1/managers/stage/stage-manager.go`)
* Integrated API client calls in `ResumeStage` to fetch activation state and update evaluation context triggers. (`api/pkg/apis/v1alpha1/managers/stage/stage-manager.go`)
* Modified `HandleTriggerEvent` to differentiate between `triggers` and `inputs`, ensuring proper handling of trigger data. (`api/pkg/apis/v1alpha1/managers/stage/stage-manager.go`)
* Updated the `traceValue` function to include `triggers` in the context for evaluation. (`api/pkg/apis/v1alpha1/managers/stage/stage-manager.go`)
* Added new …
> Add Triggers field for activation input

- cli/README.md
Problem:
- Several typos in cli/README.md
- Style of certain abbreviations is not consistent.
Solution:
- Fix typos.
- Align style of abbreviations.
Testing:
- Not required since this is a pure documentation improvement.
> Fix typos in cli/README.md and align style of abbreviations

- api/constants/constants.go
- api/pkg/apis/v1alpha1/managers/activations/activations-manager.go
- api/pkg/apis/v1alpha1/managers/catalogs/catalogs-manager.go
- api/pkg/apis/v1alpha1/managers/instances/instances-manager.go
- api/pkg/apis/v1alpha1/managers/stage/stage-manager.go
- api/pkg/apis/v1alpha1/managers/staging/staging-manager.go
- api/pkg/apis/v1alpha1/managers/targets/targets-manager.go
- api/pkg/apis/v1alpha1/model/deployableStatus.go
- api/pkg/apis/v1alpha1/model/objectmeta.go
- api/pkg/apis/v1alpha1/model/objectmeta_test.go
- api/pkg/apis/v1alpha1/providers/stage/create/create.go
- api/pkg/apis/v1alpha1/providers/stage/create/create_test.go
- api/pkg/apis/v1alpha1/providers/stage/materialize/materialize.go
- api/pkg/apis/v1alpha1/providers/states/k8s/k8s.go
- api/pkg/apis/v1alpha1/utils/symphony-api.go
- api/pkg/apis/v1alpha1/utils/utils.go
- api/pkg/apis/v1alpha1/vendors/activations-vendor.go
- docs/samples/campaigns/create/activation.yaml
- docs/samples/campaigns/create/campaign.yaml
- docs/samples/campaigns/create/solutions.yaml
- docs/samples/campaigns/create/targets.yaml
- k8s/apis/solution/v1/instance_webhook.go
- k8s/reconcilers/deployment.go
- test/integration/scenarios/04.workflow/manifest/campaign.yaml
- Materialize stage provider can be configured to wait for solution deployment on instances or targets in k8s mode. (standalone mode is not supported since standalone mode doesn't have status report mechanism right now and object generation is not bumped except in k8s state store).
-  k8s write generation along with status 
- materialize check status and generation
- Use different field for Etag and Generation in ObjectMeta.
- Etag is like ResourceVersion in k8s which changes every time when there is change on object including status
- Generation is like Generation in k8s which changes every time when object spec changes
This change depends on https://github.com/eclipse-symphony/symphony/pull/465
sample status for error case:
> Materialize stage provider can wait for solution deployment

- cli/install/install.sh
When following [basic installation instructions](https://github.com/Eclipse-SDV-Hackathon-Chapter-Two/challenge-maestro/blob/main/eclipse-symphony/README.md#installing-symphony) at a slow network, it is not clear, what happens if the screen doesn't show any progress within seconds. Therefore, I unsilenced wget/curl.
> Remove silent/quite from curl/wget at install.sh

- k8s/apis/federation/v1/catalog_webhook.go
- test/integration/scenarios/08.webhook/manifest/child-noparent.yaml
- test/integration/scenarios/08.webhook/verify/webhook_test.go
When a child catalog updated its parent information, we should update the parent label as well. If the updated spec does not contain parent catalog but the current catalog object has deprecated parent labels, we should remove the labels.
> Remove deprecated parent label when child catalog update removes parent

- api/pkg/apis/v1alpha1/managers/sites/sites-manager.go
- api/pkg/apis/v1alpha1/managers/sites/sites-manager_test.go
- api/pkg/apis/v1alpha1/model/site.go
- api/pkg/apis/v1alpha1/vendors/federation-vendor.go
Currently, site object does not preserve ETag or resource version. This will trigger k8s error if pod crashes and tries to restart because the object has no resource version and update request will fail.
Add `ObjectMeta` to site object to maintain ETag and resource version.
> update site object with ETag

- .gitmodules
> fix submodules by using https:// to replace git@ to avoid ssh config issue

- api/pkg/apis/v1alpha1/managers/solution/metrics/metrics.go
- api/pkg/apis/v1alpha1/providers/metrics/metrics.go
- coa/constants/constants.go
- coa/pkg/apis/v1alpha2/bindings/http/metrics.go
- coa/pkg/apis/v1alpha2/bindings/http/metrics/attributes.go
- coa/pkg/apis/v1alpha2/bindings/http/metrics/metrics.go
- docs/symphony-book/observability/metrics.md
- k8s/apis/metrics/v1/metrics.go
- k8s/controllers/metrics/metrics.go
1. symphony_api_operations_status, count the http status code per request uri and method. 
2. fix missing metrics close
3. emit status code dimension in symphony_api_operations_latency to better understand the latency sampling per status code.
> add new api status code metrics for SLI calculation

- api/pkg/apis/v1alpha1/managers/activations/activations-cleanup-manager.go
- api/pkg/apis/v1alpha1/managers/managerfactory.go
- api/pkg/apis/v1alpha1/managers/remote-agent/remote-agent-scheduler.go
- api/pkg/apis/v1alpha1/managers/remote-agent/remote-agent-scheudler_test.go
- api/pkg/apis/v1alpha1/model/message_types.go
- api/pkg/apis/v1alpha1/providers/target/script/script.go
- api/pkg/apis/v1alpha1/providers/target/script/script_test.go
- api/pkg/apis/v1alpha1/vendors/backgroundjob-vendor.go
- api/pkg/apis/v1alpha1/vendors/targets-vendor.go
- api/pkg/apis/v1alpha1/vendors/targets-vendor_test.go
- remote-agent/providers/remote-agent-provider.go
- remote-agent/script/instance.yaml
- remote-agent/script/mock-apply.sh
- remote-agent/script/mock-get.ps1
- remote-agent/script/mock-get.sh
- remote-agent/script/mock-remove.sh
- remote-agent/script/solution.yaml
Please review part 1 before 2
After bootstrap is done, we added SR and upgrade in the remote agent provider
We also changed the script provider a bit to allow it to run script like script stage provider (makes more sense to run custom script on remote side)
> Remote Agent Part2: add remote-agent provider to support SR and upgrade

- api/pkg/apis/v1alpha1/providers/target/rust/Cargo.toml
- api/pkg/apis/v1alpha1/providers/target/rust/rust.go
- api/pkg/apis/v1alpha1/providers/target/rust/rust_providers/ankaios/Cargo.toml
- api/pkg/apis/v1alpha1/providers/target/rust/rust_providers/ankaios/src/lib.rs
- api/pkg/apis/v1alpha1/providers/target/rust/rust_providers/mock/Cargo.toml
- api/pkg/apis/v1alpha1/providers/target/rust/rust_providers/mock/src/lib.rs
- api/pkg/apis/v1alpha1/providers/target/rust/symphony/Cargo.toml
- api/pkg/apis/v1alpha1/providers/target/rust/symphony/README.md
- api/pkg/apis/v1alpha1/providers/target/rust/symphony/include/rust_target_provider.h
- api/pkg/apis/v1alpha1/providers/target/rust/symphony/src/lib.rs
- api/pkg/apis/v1alpha1/providers/target/rust/symphony/src/models.rs
Improved several formal aspects of the Rust binding.
In particular
* added doc comments,
* made the code comply with the rustfmt rules,
* replaced println statements with tracing events.
Also removed ITargetProvider::init in favor of providing the (full)
JSON configuration to the create_provider function that is used to
create the Target Provider instance. This accounts for the fact that
it is usually a little tedious to alter internal state of an instance in
Rust.
> General improvements to the Rust binding

- k8s/apis/fabric/v1/target_webhook.go
- k8s/controllers/actions/catalogeval_controller.go
- k8s/controllers/ai/model_controller.go
- k8s/controllers/ai/skill_controller.go
- k8s/controllers/ai/skillpackage_controller.go
- k8s/controllers/fabric/device_controller.go
- k8s/controllers/fabric/target_polling_controller.go
- k8s/controllers/fabric/target_queueing_controller.go
- k8s/controllers/federation/catalog_controller.go
- k8s/controllers/federation/catalogcontainer_controller.go
- k8s/controllers/federation/site_controller.go
- k8s/controllers/monitor/diagnostic_controller.go
- k8s/controllers/solution/instance_polling_controller.go
- k8s/controllers/solution/instance_queueing_controller.go
- k8s/controllers/solution/instancehistory_controller.go
- k8s/controllers/solution/solution_controller.go
- k8s/controllers/solution/solutioncontainer_controller.go
- k8s/controllers/workflow/activation_controller.go
- k8s/controllers/workflow/campaign_controller.go
- k8s/controllers/workflow/campaigncontainer_controller.go
- k8s/reconcilers/deployment.go
* Disable RecoverPanic in controller and enable fault tests
* Skip verifying stageHistory in fault tests
* add logging
* Move readyflag after endpoint is ready
* disable pr gate and add schedule run
> [PublicPreview] Disable RecoverPanic in controller and enable fault tests (#696)

- k8s/controllers/metrics/metrics.go
- k8s/reconcilers/deployment.go
- k8s/reconcilers/deployment_test.go
Reference: https://github.com/msftcoderdjw/eclipse-symphony/pull/41
When attemptUpdate (queue) detect timeout, it should mark the timeout status by itself since updateJobId will be skipped and pollResult won't be triggered.
When pollRequest (poll) detect timeout, it should not return error to controller runtime. It can directly terminate reconciliation loop and wait for next queue.
@msftcoderdjw
> Fix timeout handling in attemptUpdate and pollResult

- api/pkg/apis/v1alpha1/providers/target/rust/rust.go
When we deserialize into RustTargetProvider, we are ignoring all extra fields. However, custom rust provider developers may rely on these extra fields to be passed into the provider as additional configurations.
> fix regression to allow extra config properties to be carried into provider
