- api/pkg/apis/v1alpha1/managers/sites/sites-manager.go
- api/pkg/apis/v1alpha1/managers/sites/sites-manager_test.go
- update status using the input value if not empty
- add test coverage
> Fix site manager reportState and add test coverage

- api/symphony-api-no-k8s.json
- api/symphony-api-production.json
- api/symphony-api.json
- packages/helm/symphony/files/symphony-api.json
The current background job runs every minute. Reduce the frequency.
> Reduce the frequency of activation cleanup background job from 1min to 1hour

- api/pkg/apis/v1alpha1/managers/staging/staging-manager.go
- coa/pkg/apis/v1alpha2/providers/queue/memory/memoryprovider.go
- coa/pkg/apis/v1alpha2/providers/queue/memory/memoryprovider_test.go
- coa/pkg/apis/v1alpha2/providers/queue/queue.go
Rename stack provider to queue provider, fix some local variables.
**Validations:**
1. UT passed
2. Integration tests passed.
> Rename stack to queue

- .github/workflows/go.yml
- api/pkg/apis/v1alpha1/providers/target/docker/docker_test.go
- api/pkg/apis/v1alpha1/providers/target/mqtt/mqtt_test.go
- coa/pkg/apis/v1alpha2/bindings/mqtt/mqtt_test.go
- Install `mosquitto` and enable Local MQTT test using `TEST_MQTT_LOCAL_ENABLED` tag
- Update docker test using `TEST_DOCKER_ENABLED` tag
> Enable local MQTT and docker test in Go pipeline

- .github/workflows/go.yml
- api/pkg/apis/v1alpha1/providers/states/k8s/k8s.go
- api/pkg/apis/v1alpha1/providers/states/k8s/k8s_test.go
1. Fix the status structure error when update target (part of https://github.com/eclipse-symphony/symphony/issues/90)
2. add unit tests for k8s state provider (IConfigProvider related logic excluded)
> Fix k8s state provider update status logic and add unit tests

- coa/pkg/apis/v1alpha2/providers/ledger/mock/mock_test.go
- coa/pkg/apis/v1alpha2/providers/queue/memory/memoryprovider_test.go
- coa/pkg/apis/v1alpha2/providers/reporter/http/httpprovider_test.go
Add unit tests for three coa providers
| component | previous(%) | now(%) |
|--------------|-----------|------|
|ledger/mock| 0 | 89.7|
|queue/memory|0|85.7|
| reporter/http|0| 84.5|
> COA unit tests

- coa/pkg/apis/v1alpha2/contexts/manager-context_test.go
- coa/pkg/apis/v1alpha2/contexts/vendor-context_test.go
- coa/pkg/apis/v1alpha2/errors_test.go
- coa/pkg/apis/v1alpha2/events_test.go
- coa/pkg/apis/v1alpha2/providers/states/httpstate/httpstate_test.go
- coa/pkg/apis/v1alpha2/request-response_test.go
- coa/pkg/apis/v1alpha2/types.go
- coa/pkg/apis/v1alpha2/types_test.go
- coa/pkg/apis/v1alpha2/utils/utils_test.go
- coa/pkg/apis/v1alpha2/vendors/vendors_test.go
**Changes**
Add tests in COA
Files | Previous (%) | Now (%)
-- | -- | -- 
./pkg/apis/v1alpha2/managers/managers.go | 0 | 100
./pkg/apis/v1alpha2/vendors/vendors.go | 0 | 95.5
./pkg/apis/v1alpha2/utils/utils.go | 0 | 100
./pkg/apis/v1alpha2/request-response.go | 0 | 100
./pkg/apis/v1alpha2/types.go | 0 | 100
./pkg/apis/v1alpha2/errors.go | 0 | 100
./pkg/apis/v1alpha2/events.go | 64 | 72
./pkg/apis/v1alpha2/contexts/manager-context.go | 0 | 100
./pkg/apis/v1alpha2/contexts/vendor-context.go | 0 | 100
> Add tests in COA

- api/pkg/apis/v1alpha1/managers/solution/solution-manager.go
- Delete state if there is not component assignments
- Take correct target while applying a deployment plan
> Delete state if there is no component assignments

- .github/workflows/go.yml
- api/pkg/apis/v1alpha1/providers/states/k8s/k8s_test.go
> Unit test for k8s state provider

- api/pkg/apis/v1alpha1/providers/stage/patch/patch.go
fix https://github.com/eclipse-symphony/symphony/issues/109
> Block configuration patch from catalog if catalog spec is not valid

- coa/pkg/apis/v1alpha2/providers/config/mock/mockprovider_test.go
- coa/pkg/apis/v1alpha2/providers/probe/rtsp/rtsp_test.go
- coa/pkg/apis/v1alpha2/providers/reference/customvision/customvision_test.go
- coa/pkg/apis/v1alpha2/providers/reference/http/httpprovider_test.go
- coa/pkg/apis/v1alpha2/providers/reference/k8s/k8sprovider_test.go
- coa/pkg/apis/v1alpha2/providers/reference/mock/mockprovider_test.go
<table>
<tr>
<th>Files</th>
<th>Previous (%)</th>
<th>Now (%)</th>
</tr>
<tr>
<td>./pkg/apis/v1alpha2/providers/config/mock/mockprovider.go</td>
<td>38.7</td>
<td>67.7</td>
</tr>
<tr>
<td>./pkg/apis/v1alpha2/providers/probe/rtsp/rtsp.go</td>
<td>46.6</td>
<td>58.9</td>
</tr>
<tr>
<td>./pkg/apis/v1alpha2/providers/reference/k8s/k8sprovider.go</td>
<td>17.6</td>
<td>75.7</td>
</tr>
<tr>
<td>./pkg/apis/v1alpha2/providers/reference/mock/mockprovider.go</td>
<td>51.2</td>
<td>70.7</td>
</tr>
<tr>
<td>./pkg/apis/v1alpha2/providers/reference/http/httpprovider.go</td>
<td>0</td>
<td>84.4</td>
</tr>
</table>
> add test for coa

- .github/workflows/sampleimages.yaml
https://github.com/eclipse-symphony/symphony/issues/168
Build sample-flask-app, symphony-python-sdk, symphony-akri images and upload them
> Add sample image pipeline

- test/localenv/magefile.go
> Fix buildAgent function in local test env

- api/pkg/apis/v1alpha1/managers/stage/stage-manager.go
> avoid crashes if stage provider is not found.

- api/pkg/apis/v1alpha1/model/summary.go
- api/pkg/apis/v1alpha1/model/summary_test.go
Fix updaetTargetResult and add test case.
> Fix update target result

- cli/go.mod
- cli/go.sum
Needs to run go mod tidy on maestro again to make it build
> mo mod tidy on maestro

- api/pkg/apis/v1alpha1/managers/reference/reference-manager.go
- api/pkg/apis/v1alpha1/managers/stage/stage-manager.go
- api/pkg/apis/v1alpha1/managers/staging/staging-manager.go
- api/pkg/apis/v1alpha1/managers/target/target-manager.go
- api/pkg/apis/v1alpha1/managers/trails/trails-manager.go
- api/pkg/apis/v1alpha1/providers/config/catalog/catalogprovider.go
- api/pkg/apis/v1alpha1/providers/stage/counter/counter.go
- api/pkg/apis/v1alpha1/providers/stage/list/list.go
- api/pkg/apis/v1alpha1/providers/stage/materialize/materialize.go
- api/pkg/apis/v1alpha1/providers/stage/remote/remote.go
- api/pkg/apis/v1alpha1/providers/stage/wait/wait.go
- api/pkg/apis/v1alpha1/providers/states/k8s/k8s.go
- api/pkg/apis/v1alpha1/providers/target/adb/adb.go
- api/pkg/apis/v1alpha1/providers/target/azure/iotedge/iotedge.go
- api/pkg/apis/v1alpha1/providers/target/docker/docker.go
- api/pkg/apis/v1alpha1/providers/target/k8s/k8s.go
- api/pkg/apis/v1alpha1/utils/parser.go
- api/pkg/apis/v1alpha1/utils/schema.go
- api/pkg/apis/v1alpha1/vendors/echovendor.go
- api/pkg/apis/v1alpha1/vendors/job-vendor.go
- coa/pkg/apis/v1alpha2/bindings/http/cors.go
- coa/pkg/apis/v1alpha2/bindings/http/http.go
- coa/pkg/apis/v1alpha2/bindings/http/metrics.go
- coa/pkg/apis/v1alpha2/providers/pubsub/redis/redis.go
- coa/pkg/apis/v1alpha2/providers/states/memorystate/memorystate.go
- coa/pkg/apis/v1alpha2/utils/utils.go
Fix https://github.com/eclipse-symphony/symphony/issues/257
> Handle type conversion errors

- k8s/apis/ai/v1/model_webhook.go
- k8s/apis/ai/v1/skill_webhook.go
- k8s/apis/fabric/v1/device_webhook.go
- k8s/apis/federation/v1/catalog_webhook.go
- k8s/apis/solution/v1/solution_webhook.go
For webhook validation, we need to return "k8s.io/apimachinery/pkg/api/errors". Otherwise, k8s would mess up the status code.
> webhook error improvement

- test/localenv/README.md
* added commands to delete temporary `.tar.gz` files, also fixed a file name mismatch
* added go environment setting up section
* before use mage command, redirect to `test/localenv` directory
> Update some commands in test/localenv/README.md to avoid errors when setting up

- api/pkg/apis/v1alpha1/providers/providerfactory.go
- api/pkg/apis/v1alpha1/providers/providerfactory_test.go
- api/pkg/apis/v1alpha1/providers/states/k8s/k8s.go
- coa/pkg/apis/v1alpha2/errors.go
- coa/pkg/apis/v1alpha2/providers/states/helpers.go
- coa/pkg/apis/v1alpha2/providers/states/memorystate/memorystate.go
- coa/pkg/apis/v1alpha2/providers/states/redisstate/redisstate.go
- coa/pkg/apis/v1alpha2/providers/states/redisstate/redisstate_test.go
- coa/pkg/apis/v1alpha2/providers/states/states.go
- go.work.sum
Use Redis HSet to restore key-value pairs. Have Upsert, Get, List, Delete implemented.
- key: namespace:resource.group:objName
- fields: etag and values
> Add redis state provider

- .github/workflows/conformance.yml
- .github/workflows/go.yml
- .github/workflows/integration.yml
- .github/workflows/suite.yml
> github workflow change: auto run on release branches

- .github/workflows/integration.yml
- api/pkg/apis/v1alpha1/providers/stage/materialize/materialize.go
- api/pkg/apis/v1alpha1/providers/stage/materialize/materialize_test.go
- api/pkg/apis/v1alpha1/vendors/catalogs-container-vendor.go
- api/pkg/apis/v1alpha1/vendors/instances-container-vendor.go
- api/pkg/apis/v1alpha1/vendors/solutions-container-vendor.go
- api/pkg/apis/v1alpha1/vendors/targets-container-vendor.go
- docs/samples/multisite/solution-catalog.yaml
- packages/helm/symphony/templates/env-configmap.yaml
- packages/helm/symphony/templates/symphony-core/symphony-api.yaml
- packages/helm/symphony/values.yaml
- test/integration/scenarios/04.workflow/magefile.go
- test/integration/scenarios/04.workflow/verify/manifest_test.go
- test/localenv/symphony-ghcr-values.yaml
We are adding the labeling feature to materialize so that users can filter the label to see what resources are created from materialize. Of course users can disable this, too.
> Add the functionality for users to set if they want to add a label to the materialized resources

- .github/workflows/integration.yml
- api/pkg/apis/v1alpha1/managers/solution/solution-manager.go
- api/pkg/apis/v1alpha1/managers/solution/solution-manager_test.go
- test/integration/lib/testhelpers/helpers.go
- test/integration/scenarios/00.unit/magefile.go
- test/integration/scenarios/01.update/magefile.go
- test/integration/scenarios/02.basic/magefile.go
- test/integration/scenarios/02.basicdelete/magefile.go
- test/integration/scenarios/02.basicdelete/manifest/instance.yaml
- test/integration/scenarios/02.basicdelete/manifest/solution.yaml
- test/integration/scenarios/02.basicdelete/manifest/target.yaml
- test/integration/scenarios/03.basicWithNsDelete/magefile.go
- test/integration/scenarios/04.workflow/magefile.go
- test/integration/scenarios/05.catalog/magefile.go
When deleting a target, deployment will not have deleted target information which causes nullref exception. Extract from mergedState which definitely contains modified target information.
Add an integration test for deleting target only.
> Fix agent lookup when deleting target

- api/pkg/apis/v1alpha1/providers/target/k8s/k8s.go
- test/integration/scenarios/03.basicWithNsDelete/manifest/oss/solution-update.yaml
- test/integration/scenarios/03.basicWithNsDelete/verify/manifest_test.go
> Make K8s target provider apply deployment if container spec changes in Solution

- test/localenv/magefile.go
Add options for 'minikube start'
> Add options for 'minikube start'

- api/pkg/apis/v1alpha1/model/objectmeta.go
- api/pkg/apis/v1alpha1/providers/stage/materialize/materialize.go
- packages/helm/symphony/templates/env-configmap.yaml
- packages/helm/symphony/values.yaml
- test/integration/scenarios/04.workflow/magefile.go
- test/integration/scenarios/04.workflow/verify/manifest_test.go
- test/localenv/symphony-ghcr-values.yaml
For nested resource sync back, we still need an azureName annotation to make it work
> add azurename annotation

- api/pkg/apis/v1alpha1/providers/stage/http/http.go
- api/pkg/apis/v1alpha1/providers/stage/http/http_test.go
> Fix input getting problem by setting content type

- packages/helm/symphony/templates/redis-configmap.yaml
- packages/helm/symphony/values.yaml
> Change redis config to be compatible with redis 6.x

- api/pkg/apis/v1alpha1/utils/symphony-api_test.go
Need to have some more dicussion on this
> fix the dependency chart for TestGetInstancesWhenSomeInstances

- api/pkg/apis/v1alpha1/providers/stage/create/create.go
> Add annotation and set namespace for providers.stage.create

- api/pkg/apis/v1alpha1/managers/solution/solution-manager.go
- api/pkg/apis/v1alpha1/model/deployment.go
- api/pkg/apis/v1alpha1/model/instance.go
- api/pkg/apis/v1alpha1/model/target.go
- api/pkg/apis/v1alpha1/utils/symphony-api.go
- api/pkg/apis/v1alpha1/validation/instance_validator.go
- api/pkg/apis/v1alpha1/validation/target_validator.go
- go.work.sum
- k8s/apis/model/v1/common_types.go
- k8s/config/oss/crd/bases/fabric.symphony_targets.yaml
- k8s/config/oss/crd/bases/solution.symphony_instances.yaml
- k8s/utils/symphony-api.go
- packages/helm/symphony/templates/symphony-core/symphonyk8s.yaml
- test/integration/scenarios/02.basic/magefile.go
- test/integration/scenarios/02.basic/manifest/oss/instance.yaml
- test/integration/scenarios/02.basic/manifest/oss/solution.yaml
- test/integration/scenarios/02.basic/manifest/oss/target.yaml
- test/integration/scenarios/02.basic/verify/manifest_test.go
1. Add isDryRun field in instance and target spec.
2. Change existing integration test to cover dryrun case.
> DryRun for instance and target

- docs/samples/canary/campaign.yaml
- docs/samples/canary/instance.yaml
- docs/samples/canary/solution.yaml
1. Added use-regx annotation
2. Updated regx syntax
3. Reduced instance reconciliation interval to 1m.
> Update canary sample for Minikube

- api/pkg/apis/v1alpha1/utils/utils.go
- api/pkg/apis/v1alpha1/utils/utils_test.go
- api/pkg/apis/v1alpha1/vendors/activations-vendor.go
- api/pkg/apis/v1alpha1/vendors/campaigns-container-vendor.go
- api/pkg/apis/v1alpha1/vendors/campaigns-vendor.go
- api/pkg/apis/v1alpha1/vendors/catalogs-container-vendor.go
- api/pkg/apis/v1alpha1/vendors/catalogs-vendor.go
- api/pkg/apis/v1alpha1/vendors/devices-vendor.go
- api/pkg/apis/v1alpha1/vendors/devices-vendor_test.go
- api/pkg/apis/v1alpha1/vendors/echovendor.go
- api/pkg/apis/v1alpha1/vendors/federation-vendor.go
- api/pkg/apis/v1alpha1/vendors/instances-vendor.go
- api/pkg/apis/v1alpha1/vendors/models-vendor.go
- api/pkg/apis/v1alpha1/vendors/skills-vendor.go
- api/pkg/apis/v1alpha1/vendors/solutions-container-vendor.go
- api/pkg/apis/v1alpha1/vendors/solutions-vendor.go
- api/pkg/apis/v1alpha1/vendors/targets-vendor.go
- coa/pkg/apis/v1alpha2/bindings/mqtt/mqtt.go
- docs/symphony-book/api/projection.md
- docs/symphony-book/api/solutions-api.md
> content type change to text/plain + add tests for utils.FormatObject

- api/symphony-api-no-k8s-munchen.json
- api/symphony-api-no-k8s-new-york.json
- api/symphony-api-no-k8s-tokyo.json
- api/symphony-api-no-k8s.json
- api/symphony-api.json
this did not match the helm install symphony-api.json either
> typo memeory vs memory

- .github/workflows/conformance.yml
- .github/workflows/go.yml
- .github/workflows/integration.yml
- .github/workflows/release.yaml
- .github/workflows/sampleimages.yaml
- .github/workflows/suite.yml
https://github.com/actions/setup-go
https://github.com/actions/checkout
> update actions/checkout@v3 -> v4 and actions/setup-go@v3 -> v5

- api/pkg/apis/v1alpha1/managers/solution/solution-manager.go
Fixing #498 timeout issue
Set components deployment `retryCount` to 1
> Set retryCount to 1

- k8s/config/oss/helm/certificate-patch.yaml
- packages/helm/symphony/templates/certificate/certificate.yaml
- packages/helm/symphony/templates/symphony-core/_helpers.tpl
- packages/helm/symphony/templates/symphony-core/symphonyk8s.yaml
- packages/helm/symphony/values.yaml
Add a configuration for cert duration time and renew cert before
> add a configure value for cert expire and renew before

- README.md
Jan 2025 Community Call Information
> Update README.md to include Jan 2025 Upcoming community call

- coa/pkg/apis/v1alpha2/utils/utils.go
- coa/pkg/apis/v1alpha2/utils/utils_test.go
Add utility function to address issue #590
> Add Unmarshal Json utility function

- api/constants/constants.go
- coa/pkg/apis/v1alpha2/bindings/http/log.go
- coa/pkg/apis/v1alpha2/bindings/http/metrics.go
- coa/pkg/apis/v1alpha2/bindings/http/metrics/attributes.go
- coa/pkg/apis/v1alpha2/bindings/http/metrics/metrics.go
- coa/pkg/apis/v1alpha2/events_test.go
- coa/pkg/apis/v1alpha2/request-response_test.go
- coa/pkg/logger/contexts/activitylog-context.go
- coa/pkg/logger/contexts/contexts_test.go
- coa/pkg/logger/contexts/decorators_test.go
- coa/pkg/logger/contexts/log-context-decorator.go
- coa/pkg/logger/hooks/hooks_test.go
- k8s/constants/constants.go
- k8s/utils/diagnostic/helper.go
This is a quick fix to downstream extension side, will backport to main branch after holiday.
> sli requires customer resource id and location id

- api/pkg/apis/v1alpha1/managers/stage/stage-manager.go
> Skip stage checking

- api/pkg/apis/v1alpha1/managers/jobs/jobs-manager.go
- api/pkg/apis/v1alpha1/model/deployment.go
- api/pkg/apis/v1alpha1/model/deployment_test.go
- api/pkg/apis/v1alpha1/utils/apiclient.go
> Improve the log in QueueDeploymentJob to avoid user private data exposed

- api/pkg/apis/v1alpha1/utils/apiclient.go
> Add retry mechanism for rest API calls

- packages/helm/symphony/files/oss/wait-api.sh
- packages/helm/symphony/templates/symphony-core/symphonyk8s-controller.yaml
- packages/helm/symphony/templates/symphony-core/symphonyk8s.yaml
(cherry picked from commit c0999361c7bae4cf11734739c77a1f0eea6c41d6)
> [TEMP] k8s wait for api pod

- README.md
- api/pkg/apis/v1alpha1/vendors/activations-vendor.go
- api/pkg/apis/v1alpha1/vendors/activations-vendor_test.go
- api/symphony-api-no-k8s-munchen.json
- api/symphony-api-no-k8s-new-york.json
- api/symphony-api-no-k8s-tokyo.json
- api/symphony-api-no-k8s.json
- docs/samples/campaigns/counter/README.md
- docs/samples/campaigns/counter/activation.json
- docs/samples/campaigns/counter/campaign-container.json
- docs/samples/campaigns/counter/campaign.json
> avoid duplicated campaign activation when calling REST while hosted on K8s

- packages/helm/symphony/templates/symphony-core/symphony-api.yaml
- packages/helm/symphony/templates/symphony-core/symphony-service-ext.yaml
- packages/helm/symphony/templates/symphony-core/symphony-service.yaml
- packages/helm/symphony/values.yaml
it would be open by default unless we explicitly set it to false
> close http ports based on the openHTTP

- api/pkg/apis/v1alpha1/providers/target/helm/helm.go
- api/pkg/apis/v1alpha1/providers/target/helm/helm_test.go
> Helm add release name
